In [1]:
import numpy as np

In [2]:
np.array([1,2,3]) #creates a numpy array

array([1, 2, 3])

In [3]:
arr = np.array(32)
arr.ndim #gives the dimensionality

0

In [4]:
arr = np.array([1,2,3])
arr.ndim

1

In [5]:
arr = np.arange(1,10) #creates an array within the given range 
print(arr)

[1 2 3 4 5 6 7 8 9]


In [6]:
arr = np.arange(1,50,5)
print(arr)

[ 1  6 11 16 21 26 31 36 41 46]


In [8]:
np.zeros(5) # creates an array with full of zeros

array([0., 0., 0., 0., 0.])

In [9]:
np.zeros([2,3]) 

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.ones([2,3],dtype = int) #creates an array with full of ones of integer type

array([[1, 1, 1],
       [1, 1, 1]])

In [11]:
np.ones([2,3]) #creates an array with full of ones 

array([[1., 1., 1.],
       [1., 1., 1.]])

In [12]:
np.full(10, 5) # creates an array full of values that are provided 

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [13]:
np.full([2,4], 5) #[row, column], default value

array([[5, 5, 5, 5],
       [5, 5, 5, 5]])

In [14]:
np.empty([2,4]) #creates an array without setting any values ->this is not zeroes array It is uninitialized array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
np.random.rand(10) # generates 10 random float values betwee 0 and 1

array([0.04271694, 0.36006057, 0.89075265, 0.84922809, 0.0374836 ,
       0.52412715, 0.0669936 , 0.68995175, 0.9128927 , 0.11886255])

In [17]:
np.random.rand(2,3) # crates a 2-D array

array([[0.19314655, 0.15929027, 0.05709786],
       [0.69069848, 0.67458162, 0.07223998]])

In [18]:
np.random.randn(2,3) #random floats from standard normal distribution

array([[-0.68978415,  1.19768849, -0.24479132],
       [ 2.30532743, -1.00447436,  0.49222326]])

In [19]:
np.random.randint(1, 100, size=(2,2)) #generates a random array with in the given range of specified size

array([[77, 29],
       [ 2, 32]])

In [20]:
arr = np.array([1,2,3.5,4])
print(arr)

[1.  2.  3.5 4. ]


In [21]:
print(type(arr))

<class 'numpy.ndarray'>


In [3]:
import numpy as np
#creation of multi dimensional array
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
#Reshape
arr = np.array([1,2,3,4,5,6])
reshaped = arr.reshape(2,3)

In [8]:
print(reshaped)

[[1 2 3]
 [4 5 6]]


In [9]:
#ravel convertes given array to 1D array
#ravel returns view 
ravel = reshaped.ravel()
print(ravel)

[1 2 3 4 5 6]


In [10]:
ravel[0] = 100
print(ravel)

[100   2   3   4   5   6]


In [12]:
# faltten returns copy 
#flaten converts to 1D array
flat = reshaped.flatten()
flat

array([100,   2,   3,   4,   5,   6])

In [13]:
flat[0] = 1
print(flat)

[1 2 3 4 5 6]


In [14]:
reshaped

array([[100,   2,   3],
       [  4,   5,   6]])

In [15]:
#Arithmetic operations
a = np.array([1,2,3])
b = np.array([4,5,6])


In [16]:
#Addition
print(a+b)

[5 7 9]


In [17]:
#Subtarction
print(a-b)

[-3 -3 -3]


In [18]:
#Multiplication
print(a*b)

[ 4 10 18]


In [19]:
#Universal Functions -> ufuncs
arr = np.array([1,4,9,16])

In [22]:
print(np.sqrt(arr))

[1. 2. 3. 4.]


In [23]:
#indexing and slicing
arr = np.array([10,20,30,40,50])

In [25]:
arr[::2]

array([10, 30, 50])

In [26]:
#multidimensional slicing
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [27]:
print(matrix[0:2, : ])

[[1 2 3]
 [4 5 6]]


In [28]:
#np.take() -> built-in function to perform indexing and slicing
arr = np.array([10,20,30,40,50])
ind = [0,2]
print(np.take(arr, ind))

[10 30]


In [29]:
#iterating using nditer()
arr = np.array([[1,2],[3,4]])

In [30]:
for x in np.nditer(arr):
    print(x, end = " ")

1 2 3 4 

In [35]:
#ndenumerate() -> returns both the index and value
arr = np.array([[1,2],[3,4]])
for ind, x in np.ndenumerate(arr):
    print(ind,x)

(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4


In [36]:
#Transpose of a matrix -> np.transpose()
arr = np.array([[1,2],[3,4]])
print(arr)
print(arr.transpose())

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [37]:
#Swapaxes -> swap 2 speific axes in a matrix
arr = np.array([[[1,2],[3,4]]])
arr.shape

(1, 2, 2)

In [38]:
swap = np.swapaxes(arr, 0, 1)
swap.shape

(2, 1, 2)

In [40]:
#Concaenation -> np.concatenate(a,b)
a = np.array([1,2])
b = np.array([3,4])
print(np.concatenate((a,b)))

[1 2 3 4]


In [41]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
print(np.vstack((arr1,arr2)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [42]:
print(np.hstack((arr1, arr2)))

[[1 2 5 6]
 [3 4 7 8]]


In [44]:
arr = np.array([[1,2],[3,4],[5,6],[7,8]])
print(np.split(arr, 2))

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]


In [45]:
#Repeating -> repeats each element for given number of times

arr = np.array([1,2,3])
print(np.repeat(arr, 3))

[1 1 1 2 2 2 3 3 3]


In [46]:
#tile -> repeats the whole array for given number of times
print(np.tile(arr, 2))

[1 2 3 1 2 3]


In [47]:
#Condiion based
#Where

arr = np.array([1,2,3])
result = np.where(arr < 2, "low", "high")
print(result)

['low' 'high' 'high']


In [1]:
import numpy as np

In [4]:
##create an array with one on the border and 0 inside 
matrix = np.zeros((5,5))
matrix

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
matrix[:1 , :] = 1
matrix[-1:, :] = 1
matrix[:, :1] = 1
matrix[:, -1:] = 1

In [10]:
matrix

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
#to add a border of zeroes around an existing array
matrix = np.zeros((3,3))
matrix

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
arr = np.pad(matrix, pad_width = 1, mode = 'constant', constant_values = 1)
arr

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
#To create a 8*8 matrix and fill it with checker board pattern
matrix = np.zeros((8,8))
matrix

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [15]:
matrix[1::2, ::2] = 1
matrix[::2, 1::2] = 1
matrix

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [22]:
arr = np.array([10,20,30,40,50], dtype = 'int64')
arr.size

5

In [23]:
arr.itemsize

8

In [24]:
arr.size * arr.itemsize

40