In [1]:
import numpy as np

In [2]:
np.random.seed(40)
sales = np.random.randint(-100, 500, size= (30,5))

print(sales)

[[226 119 -93  65 340]
 [206 168 431 -45 343]
 [ -9 -27 229 -92 336]
 [107 170 400 -78  31]
 [467 141 409 312 110]
 [107 351 442 -40 200]
 [330 243 405 126 443]
 [110   8 -20 291  -1]
 [377  17 111 469 -43]
 [-17 448 257 385 475]
 [284 413 317 -28 -43]
 [446 170 145  84 114]
 [496 238 168 410 101]
 [150  19  15 284  -6]
 [444 206 406 176 197]
 [262 490 211  71 247]
 [-24 411 457 -93 473]
 [ 53 147 254 300 217]
 [ 79   7 278 325 305]
 [257 443 131 251 480]
 [287   5  34  -6 222]
 [403 111  30  34  23]
 [142 -75 340  78 124]
 [337 194 -33  23 -39]
 [ 38 208 196 141 413]
 [ 80 178 180 249 486]
 [-11 134 380 327 476]
 [227  34 320 105 158]
 [476 487  -3 493  56]
 [495 305 150 119 365]]


In [3]:
#Replace negative values with 0
replace = np.where(sales < 0, 0, sales)
replace

array([[226, 119,   0,  65, 340],
       [206, 168, 431,   0, 343],
       [  0,   0, 229,   0, 336],
       [107, 170, 400,   0,  31],
       [467, 141, 409, 312, 110],
       [107, 351, 442,   0, 200],
       [330, 243, 405, 126, 443],
       [110,   8,   0, 291,   0],
       [377,  17, 111, 469,   0],
       [  0, 448, 257, 385, 475],
       [284, 413, 317,   0,   0],
       [446, 170, 145,  84, 114],
       [496, 238, 168, 410, 101],
       [150,  19,  15, 284,   0],
       [444, 206, 406, 176, 197],
       [262, 490, 211,  71, 247],
       [  0, 411, 457,   0, 473],
       [ 53, 147, 254, 300, 217],
       [ 79,   7, 278, 325, 305],
       [257, 443, 131, 251, 480],
       [287,   5,  34,   0, 222],
       [403, 111,  30,  34,  23],
       [142,   0, 340,  78, 124],
       [337, 194,   0,  23,   0],
       [ 38, 208, 196, 141, 413],
       [ 80, 178, 180, 249, 486],
       [  0, 134, 380, 327, 476],
       [227,  34, 320, 105, 158],
       [476, 487,   0, 493,  56],
       [495, 3

In [14]:
#Compute the average weekly sales per product (assume 7 days = 1 week)
weekly_sales = replace[:28].reshape(4, 7, 5)
weekly_average_sales =weekly_sales.mean(axis = 1)
weekly_average_sales

array([[206.14285714, 170.28571429, 330.85714286,  71.85714286,
        257.57142857],
       [266.14285714, 187.57142857, 144.71428571, 274.71428571,
         98.57142857],
       [197.42857143, 244.14285714, 253.        , 160.42857143,
        305.85714286],
       [175.28571429, 122.71428571, 206.57142857, 136.71428571,
        240.        ]])

In [36]:
#Identify the product with the highest average weekly sales
product_average_sales = weekly_average_sales.mean(axis = 0)
print(product_average_sales)
highest_average_sales = product_average_sales.max()
highest_average_sales

[211.25       181.17857143 233.78571429 160.92857143 225.5       ]


233.78571428571428

In [19]:
np.random.seed(2)
marks = np.random.randint(0, 100, size = (200, 6))

In [23]:
total_scores = np.sum(marks, axis = 1)
total_scores

array([274, 335, 336, 240, 353, 393, 328, 366, 120, 461, 195, 299, 296,
       367, 378, 522, 308, 297, 250, 177, 351, 336, 356, 445, 268, 359,
       291, 321, 313, 262, 285, 278, 237, 275, 219, 232, 284, 247, 420,
       392, 197, 345, 286, 272, 405, 235, 411, 214, 242, 309, 390, 184,
       341, 374, 356, 310, 307, 258, 265, 380, 333, 261, 268, 286, 315,
       245, 167, 292, 369, 284, 328, 370, 154, 312, 356, 289, 362, 433,
       437, 331, 271, 342, 266, 334, 201, 292, 290, 126, 399, 233, 309,
       325, 145, 301, 291,  77, 281, 292, 266, 277, 341, 374, 242, 208,
       273, 292, 335, 224, 354, 325, 284, 275, 401, 379, 318, 346, 246,
       342, 314, 377, 233, 330, 332, 335, 280, 331, 381, 272, 211, 273,
       339, 347, 332, 415, 330, 293, 296, 369, 282, 177, 275, 314, 217,
       152, 356, 158, 255, 383, 321, 255, 340, 311, 368, 327, 268, 341,
       297, 389, 317, 157, 344, 309, 317, 243, 332, 259, 419, 449, 266,
       419, 371, 202, 323, 350, 219, 266, 227, 351, 336, 231, 34

In [26]:
percentage = (total_scores / 600) * 100
np.round(percentage, 3)

array([45.667, 55.833, 56.   , 40.   , 58.833, 65.5  , 54.667, 61.   ,
       20.   , 76.833, 32.5  , 49.833, 49.333, 61.167, 63.   , 87.   ,
       51.333, 49.5  , 41.667, 29.5  , 58.5  , 56.   , 59.333, 74.167,
       44.667, 59.833, 48.5  , 53.5  , 52.167, 43.667, 47.5  , 46.333,
       39.5  , 45.833, 36.5  , 38.667, 47.333, 41.167, 70.   , 65.333,
       32.833, 57.5  , 47.667, 45.333, 67.5  , 39.167, 68.5  , 35.667,
       40.333, 51.5  , 65.   , 30.667, 56.833, 62.333, 59.333, 51.667,
       51.167, 43.   , 44.167, 63.333, 55.5  , 43.5  , 44.667, 47.667,
       52.5  , 40.833, 27.833, 48.667, 61.5  , 47.333, 54.667, 61.667,
       25.667, 52.   , 59.333, 48.167, 60.333, 72.167, 72.833, 55.167,
       45.167, 57.   , 44.333, 55.667, 33.5  , 48.667, 48.333, 21.   ,
       66.5  , 38.833, 51.5  , 54.167, 24.167, 50.167, 48.5  , 12.833,
       46.833, 48.667, 44.333, 46.167, 56.833, 62.333, 40.333, 34.667,
       45.5  , 48.667, 55.833, 37.333, 59.   , 54.167, 47.333, 45.833,
      

In [27]:
#Assign grades using vectorized operations
grades = np.where(percentage >= 90, 'A', 
         np.where(percentage >= 75, 'B',
         np.where(percentage >= 60, 'C',
         np.where(percentage >= 40, 'D', 'F'))))
print(grades)

['D' 'D' 'D' 'D' 'D' 'C' 'D' 'C' 'F' 'B' 'F' 'D' 'D' 'C' 'C' 'B' 'D' 'D'
 'D' 'F' 'D' 'D' 'D' 'C' 'D' 'D' 'D' 'D' 'D' 'D' 'D' 'D' 'F' 'D' 'F' 'F'
 'D' 'D' 'C' 'C' 'F' 'D' 'D' 'D' 'C' 'F' 'C' 'F' 'D' 'D' 'C' 'F' 'D' 'C'
 'D' 'D' 'D' 'D' 'D' 'C' 'D' 'D' 'D' 'D' 'D' 'D' 'F' 'D' 'C' 'D' 'D' 'C'
 'F' 'D' 'D' 'D' 'C' 'C' 'C' 'D' 'D' 'D' 'D' 'D' 'F' 'D' 'D' 'F' 'C' 'F'
 'D' 'D' 'F' 'D' 'D' 'F' 'D' 'D' 'D' 'D' 'D' 'C' 'D' 'F' 'D' 'D' 'D' 'F'
 'D' 'D' 'D' 'D' 'C' 'C' 'D' 'D' 'D' 'D' 'D' 'C' 'F' 'D' 'D' 'D' 'D' 'D'
 'C' 'D' 'F' 'D' 'D' 'D' 'D' 'C' 'D' 'D' 'D' 'C' 'D' 'F' 'D' 'D' 'F' 'F'
 'D' 'F' 'D' 'C' 'D' 'D' 'D' 'D' 'C' 'D' 'D' 'D' 'D' 'C' 'D' 'F' 'D' 'D'
 'D' 'D' 'D' 'D' 'C' 'C' 'D' 'C' 'C' 'F' 'D' 'D' 'F' 'D' 'F' 'D' 'D' 'F'
 'D' 'D' 'D' 'D' 'F' 'D' 'D' 'C' 'D' 'F' 'C' 'D' 'D' 'F' 'D' 'D' 'F' 'F'
 'F' 'D']


In [30]:
#Identify top 10% performers
cut_off = np.percentile(percentage, 90)
top_10_performers = percentage >= cut_off
percentage[top_10_performers]

array([65.5       , 76.83333333, 87.        , 74.16666667, 70.        ,
       65.33333333, 67.5       , 68.5       , 65.        , 72.16666667,
       72.83333333, 66.5       , 66.83333333, 69.16666667, 63.83333333,
       64.83333333, 69.83333333, 74.83333333, 69.83333333, 73.16666667,
       63.83333333])

In [1]:
import numpy as np
np.random.seed(1)
ratings = np.random.randint(1,6, size = (4,25))
ratings

array([[4, 5, 1, 2, 4, 1, 1, 2, 5, 5, 2, 3, 5, 3, 5, 4, 5, 3, 5, 3, 5, 2,
        2, 1, 2],
       [2, 2, 2, 1, 5, 2, 1, 1, 4, 3, 2, 1, 4, 2, 2, 4, 5, 1, 2, 4, 5, 3,
        5, 1, 4],
       [2, 3, 1, 5, 2, 3, 3, 2, 1, 2, 4, 5, 4, 2, 4, 1, 1, 3, 3, 2, 4, 5,
        3, 1, 1],
       [2, 2, 4, 1, 1, 5, 3, 5, 4, 4, 1, 4, 5, 4, 5, 5, 5, 2, 1, 5, 3, 1,
        3, 5, 2]])

In [4]:
normalize_ratings = (ratings - ratings.min()) / (ratings.max() - ratings.min())

In [5]:
#Normalize the ratings using min-max normalization
normalize_ratings

array([[0.75, 1.  , 0.  , 0.25, 0.75, 0.  , 0.  , 0.25, 1.  , 1.  , 0.25,
        0.5 , 1.  , 0.5 , 1.  , 0.75, 1.  , 0.5 , 1.  , 0.5 , 1.  , 0.25,
        0.25, 0.  , 0.25],
       [0.25, 0.25, 0.25, 0.  , 1.  , 0.25, 0.  , 0.  , 0.75, 0.5 , 0.25,
        0.  , 0.75, 0.25, 0.25, 0.75, 1.  , 0.  , 0.25, 0.75, 1.  , 0.5 ,
        1.  , 0.  , 0.75],
       [0.25, 0.5 , 0.  , 1.  , 0.25, 0.5 , 0.5 , 0.25, 0.  , 0.25, 0.75,
        1.  , 0.75, 0.25, 0.75, 0.  , 0.  , 0.5 , 0.5 , 0.25, 0.75, 1.  ,
        0.5 , 0.  , 0.  ],
       [0.25, 0.25, 0.75, 0.  , 0.  , 1.  , 0.5 , 1.  , 0.75, 0.75, 0.  ,
        0.75, 1.  , 0.75, 1.  , 1.  , 1.  , 0.25, 0.  , 1.  , 0.5 , 0.  ,
        0.5 , 1.  , 0.25]])

In [6]:
#Calculate the average ratings per employee
average_rating = ratings.mean(axis = 0)
average_rating

array([2.5 , 3.  , 2.  , 2.25, 3.  , 2.75, 2.  , 2.5 , 3.5 , 3.5 , 2.25,
       3.25, 4.5 , 2.75, 4.  , 3.5 , 4.  , 2.25, 2.75, 3.5 , 4.25, 2.75,
       3.25, 2.  , 2.25])

In [7]:
#Identify employees whose average rating is above the company mean
company_mean = ratings.mean()
company_mean

2.97

In [12]:
employees = average_rating[np.where(average_rating > company_mean)]
employees

array([3.  , 3.  , 3.5 , 3.5 , 3.25, 4.5 , 4.  , 3.5 , 4.  , 3.5 , 4.25,
       3.25])

In [15]:
np.random.seed(3)
temparature = np.random.randint(-20, 50, size=(7,24))
temparature

array([[  4, -17,  36, -20,   1,  -1,  21, -10,   1,  18,   0,  24,  19,
         -6,   6,   2,  46, -18,  43,  40, -19,  31,  49,   9],
       [  4,  42, -13,  23,  13,  28,  17,   0,  29,   1,   8,  34, -20,
         44,  -2,  43,  17,  36,  36,  17,  26,  13, -19,  -4],
       [ 12,  -4,  -2,  35,  -7,  17,  10,  28,  41,  13,  32, -18,   8,
         16,  24,  28,  39,  34,   1,  36,  19,   9,  12,  28],
       [-11,  13,  40,  35,  -9, -10,  48,  24,  24,  -1,  -4,  19,  30,
         45,  15,  25,  32, -19,  -2,  43, -18,   0,  42,   2],
       [-13,  37,  23,  12,  40,  -4,   7,  33, -12,   0, -12,   4,  -1,
        -11,   6,  30,  40, -15, -11,  12,  -7,  24,  16,  22],
       [  6,   4,   0,  42,  24,  10,  -3,  12,  33,  19,  40,  12,  13,
         31,  -9,  -3,  31,  -7,  48,  43,  21,  -7,  40,  27],
       [ 16,  35,  36,  -8,   8, -10,  -9,  15,  29,  14,  -9,  39, -16,
        -20,  36,  25,   1,  14,   9,  22, -13,  10,  19,  37]])

In [17]:
#Find the daily maximum and minimum temperature
maximum_temparatures = temparature.max(axis = 1)
minimum_temparatures = temparature.min(axis = 1)
print(f"Maximum Temperatures : {maximum_temparatures}")
print(f"Minimum Temperatures : {minimum_temparatures}")

Maximum Temperatures : [49 44 41 48 40 48 39]
Minimum Temperatures : [-20 -20 -18 -19 -15  -9 -20]


In [19]:
daily_variation = temparature.max(axis=1) - temparature.min(axis=1)
print(f"Daily Temparature variations : {daily_variation}")

Daily Temparature variations : [69 64 59 67 55 57 59]


In [20]:
#Identify the day with the largest temperature variation
largest_temparature_variation = np.argmax(daily_variation)
print(f"Day with largest temparature variation : {largest_temparature_variation}")

Day with largest temparature variation : 0


In [30]:
#Replace outliers beyond ±2 standard deviations with the mean temperature
mean_temperature = temparature.mean()
std_deviation = temparature.std()
print(mean_temperature)
print(std_deviation)

13.886904761904763
19.011095004671457


In [31]:
lower_bound = mean_temperature - 2 * std_deviation
upper_bound = mean_temperature + 2 * std_deviation
print(lower_bound)
print(upper_bound)

-24.13528524743815
51.90909477124768


In [28]:
cleaned_temperature = np.where((temparature < lower_bound) | (temparature > upper_bound), mean_temperature, temparature)
print(cleaned_temperature)

[[  4. -17.  36. -20.   1.  -1.  21. -10.   1.  18.   0.  24.  19.  -6.
    6.   2.  46. -18.  43.  40. -19.  31.  49.   9.]
 [  4.  42. -13.  23.  13.  28.  17.   0.  29.   1.   8.  34. -20.  44.
   -2.  43.  17.  36.  36.  17.  26.  13. -19.  -4.]
 [ 12.  -4.  -2.  35.  -7.  17.  10.  28.  41.  13.  32. -18.   8.  16.
   24.  28.  39.  34.   1.  36.  19.   9.  12.  28.]
 [-11.  13.  40.  35.  -9. -10.  48.  24.  24.  -1.  -4.  19.  30.  45.
   15.  25.  32. -19.  -2.  43. -18.   0.  42.   2.]
 [-13.  37.  23.  12.  40.  -4.   7.  33. -12.   0. -12.   4.  -1. -11.
    6.  30.  40. -15. -11.  12.  -7.  24.  16.  22.]
 [  6.   4.   0.  42.  24.  10.  -3.  12.  33.  19.  40.  12.  13.  31.
   -9.  -3.  31.  -7.  48.  43.  21.  -7.  40.  27.]
 [ 16.  35.  36.  -8.   8. -10.  -9.  15.  29.  14.  -9.  39. -16. -20.
   36.  25.   1.  14.   9.  22. -13.  10.  19.  37.]]


In [32]:
np.random.seed(3)
time_spent = np.random.randint(0, 500, size = (14, 6))
time_spent

array([[362, 152, 249, 131, 440, 456],
       [256, 277, 147, 202, 363, 169],
       [138, 405, 119, 422, 480, 148],
       [428,  93, 423, 398,  26, 337],
       [474, 150, 322, 258, 447, 316],
       [129, 435, 346,  69, 360, 110],
       [ 97, 413, 106, 152, 318,   7],
       [171,  33, 379, 335, 176, 293],
       [ 20, 350,  49, 405, 383, 206],
       [ 28, 375,  54,   0, 192, 489],
       [274, 372, 447, 165, 184, 440],
       [455, 165, 253, 174,  33, 113],
       [  1, 341, 117, 375, 458, 235],
       [380, 484,  99, 219, 400, 336]])

In [38]:
#compute total time spent per course
time_spent_per_course = time_spent.sum(axis = 0)
print("Total time spent per course")
print(time_spent_per_course)

Total time spent per course
[3213 4045 3110 3305 4260 3655]


In [36]:
#Identify courses where average daily engagement exceeds a threshold
thresold = np.percentile(time_spent, 50)
daily_engagement = time_spent.mean(axis = 0)
courses = np.where(daily_engagement > thresold) 
courses

(array([1, 4, 5], dtype=int64),)

In [39]:
#Rank courses based on engagement
average_engagement = time_spent.mean(axis = 0)
average_engagement

array([229.5       , 288.92857143, 222.14285714, 236.07142857,
       304.28571429, 261.07142857])

In [40]:
rank = np.argsort(average_engagement)[::-1]
rank

array([4, 1, 5, 3, 0, 2], dtype=int64)

In [41]:
np.random.seed(0)
transaction = np.random.randint(-5000, 5000, size = (20, 50))
transaction

array([[-2268,  4845, -1736,  -141,  4225,  2891,  -627,   874,  1744,
        -1532, -4295, -2401, -2778,  2768, -2103,  4893, -4463,  1216,
         1921,  1036, -2837,    72,  -149,  2877, -2954, -3129,  2599,
        -2504,  3291, -4245, -4203, -4341, -1781,  3615,  2456, -1663,
        -2255,  -265,  3736,  1687, -4286, -2708,  3343, -3793,  1172,
         3994,  2221,  1021, -1378, -1440],
       [ 3948, -3359,   -16,  -647,  3622,  2250,  -813, -2341,  4781,
        -2044, -2749,  -580,  2108, -3929,   251,  2012,  4396, -1082,
         4359, -3316,  2098, -2043,  -531,  3752,  4797,   795, -3528,
         2263,  2365,  3448,  1001, -1238,  4008, -2565, -3366, -4027,
         -536,  3393, -2582, -1545,  1167,   819,  1521,  1242,  2742,
         4123,  1738, -2213,  2316,  -695],
       [-2390,   531,  1926,  2204,  1922,  -818, -4693,   302, -3848,
         1950,  3467,   294, -3792, -2508,  3829, -4230,  3286,   995,
        -2656, -1909, -1088, -3566,  1594,   368,  3372,  21

In [42]:
#Separate debit and credit transactions
credits = np.where(transaction > 0, transaction, 0)
debits = np.where(transaction < 0, transaction, 0)
print("Credits : ")
print(credits)
print("Debits : ")
print(debits)

Credits : 
[[   0 4845    0    0 4225 2891    0  874 1744    0    0    0    0 2768
     0 4893    0 1216 1921 1036    0   72    0 2877    0    0 2599    0
  3291    0    0    0    0 3615 2456    0    0    0 3736 1687    0    0
  3343    0 1172 3994 2221 1021    0    0]
 [3948    0    0    0 3622 2250    0    0 4781    0    0    0 2108    0
   251 2012 4396    0 4359    0 2098    0    0 3752 4797  795    0 2263
  2365 3448 1001    0 4008    0    0    0    0 3393    0    0 1167  819
  1521 1242 2742 4123 1738    0 2316    0]
 [   0  531 1926 2204 1922    0    0  302    0 1950 3467  294    0    0
  3829    0 3286  995    0    0    0    0 1594  368 3372 2148 2997    0
  3032 3131    0  116    0    0 4837    0 4744    0   21    0    0 4680
     0    0    0 4661    0    0  627 1265]
 [ 446    0 3717    0    0  272    0 1185    0    0    0    0  249 3408
  3216  103 2939    0    0 1118  846    0    0    0 2179 1356    0    0
  3962    0    0 4013    0    0    0  661    0    0 3067    0 3922 1

In [43]:
#Compute daily net balance changes
net_balance = transaction.sum(axis = 1)
net_balance

array([ -7778,  25570,  -4256, -31865, -13523,  20531,   9844, -24606,
        -7762,  41485,  32907,  21306,  14328,  13696,  31258,   4664,
       -11231, -17036, -10494,  -1692])

In [45]:
#Identify accounts with continuous negative balance trends
cumulative_balance = np.cumsum(transaction, axis=0)
daily_diff = np.diff(cumulative_balance, axis=0)
continuous_negative = np.all(daily_diff < 0, axis=0)
negative_trend_accounts = np.where(continuous_negative)[0]
print("Accounts with continuous negative balance trend:")
print(negative_trend_accounts)

Accounts with continuous negative balance trend:
[]


In [46]:
np.random.seed(0)
stock_prices = np.random.randint(0, 100000, size = (90, 10))
stock_prices

array([[68268, 43567, 42613, 45891, 21243, 95939, 97639, 41993, 86293,
        55026],
       [80471, 80966, 48600, 39512, 52620, 80186, 17089, 32230, 18983,
        89688],
       [82457, 93005,  6921, 38804, 67699, 70608, 37619,  7877, 83966,
         1871],
       [73135,  2496, 47954, 24675, 31921, 99059,   797, 49811, 68755,
        80782],
       [90535, 81857, 52489, 84665, 41504, 49866, 84212, 96766, 11723,
        43890],
       [17591, 58146, 92288, 59300, 89141, 71557, 20006,  3560, 90868,
        61713],
       [96591, 45444, 46522, 86904, 20737, 28647, 61353, 92217, 80163,
        12134],
       [60535, 47883, 86107, 63360, 51811,  9781, 19340, 27257, 16298,
        12372],
       [ 4420, 82991, 62079, 79860,  7012,  9396,  3918,  9359, 44259,
        23482],
       [15127, 37237, 79701,  8752, 80041, 71331, 50624, 89183, 40133,
        93790],
       [55153, 62756, 90928, 81757, 84355, 99938, 48682, 66509, 86384,
        75751],
       [76693, 24777, 13824,  2418, 12843, 

In [47]:
#Calculate daily returns
daily_returns = stock_prices.sum(axis = 1)
daily_returns

array([598472, 540345, 490827, 479385, 637507, 564170, 570712, 394744,
       326776, 565919, 752213, 401809, 540710, 696337, 540918, 472456,
       564787, 406556, 359872, 459013, 424558, 488025, 641909, 544166,
       612224, 561630, 539805, 557661, 514233, 647140, 757047, 581010,
       385639, 468827, 605049, 410235, 405237, 624992, 387999, 570048,
       678052, 438405, 603512, 443435, 410630, 610346, 519321, 550457,
       546723, 471972, 435517, 525738, 582442, 578875, 517779, 536331,
       534815, 608910, 381939, 431394, 598812, 678168, 511490, 572953,
       388033, 569058, 519839, 220048, 459862, 523024, 575089, 285734,
       434088, 545438, 381315, 493846, 500216, 496271, 505382, 522452,
       636642, 673819, 522520, 584721, 552688, 549461, 493179, 568145,
       467800, 425694])

In [49]:
#Compute volatility (standard deviation) per stock
std_deviation = stock_prices.std(axis = 0)
std_deviation

array([28749.19535059, 30361.40911441, 28747.44376329, 26879.55897686,
       27789.92900443, 27957.06322721, 29003.39782288, 29723.5505898 ,
       28578.53897024, 30547.25167205])

In [51]:
#Identify the stock with the highest risk
highest_risk = np.argmax(std_deviation)
highest_risk

9

In [52]:
np.random.seed(0)
heart_rate = np.random.randint(50, 120, size=(60, 24)).astype(float)

# Introduce missing values
heart_rate[heart_rate < 55] = np.nan

heart_rate

array([[ 94.,  97., 114., ...,  79.,  69.,  69.],
       [ 64.,  89.,  82., ...,  92., 108.,  81.],
       [ nan, 115.,  91., ...,  73.,  63.,  98.],
       ...,
       [ 72.,  81.,  84., ...,  87.,  nan, 100.],
       [111.,  78.,  85., ..., 102.,  73.,  91.],
       [110.,  97.,  65., ...,  64., 113.,  93.]])

In [53]:
#Compute hourly average heart rate
hourly_avg = np.nanmean(heart_rate, axis=0)
print("Hourly average heart rate:")
print(hourly_avg)

Hourly average heart rate:
[84.0754717  83.61403509 87.32727273 85.7        85.875      87.11538462
 86.27272727 90.61818182 83.72727273 88.83050847 85.66666667 87.03703704
 85.75       84.66037736 87.69811321 81.63636364 83.9245283  87.60377358
 86.39285714 86.70909091 88.58181818 88.03571429 87.28813559 93.26315789]


In [54]:
#Detect abnormal readings outside the normal range
abnormal_readings = (heart_rate < 60) | (heart_rate > 100)
print("Abnormal readings (True = abnormal):")
print(abnormal_readings)

Abnormal readings (True = abnormal):
[[False False  True ... False False False]
 [False False False ... False  True False]
 [False  True False ... False False False]
 ...
 [False False False ... False False False]
 [ True False False ...  True False False]
 [ True False False ... False  True False]]


In [55]:
#Replace missing values using forward fill logic
filled_heart_rate = heart_rate.copy()

for i in range(1, filled_heart_rate.shape[1]):
    mask = np.isnan(filled_heart_rate[:, i])
    filled_heart_rate[mask, i] = filled_heart_rate[mask, i - 1]

print("Heart rate after forward fill:")
print(filled_heart_rate)


Heart rate after forward fill:
[[ 94.  97. 114. ...  79.  69.  69.]
 [ 64.  89.  82. ...  92. 108.  81.]
 [ nan 115.  91. ...  73.  63.  98.]
 ...
 [ 72.  81.  84. ...  87.  87. 100.]
 [111.  78.  85. ... 102.  73.  91.]
 [110.  97.  65. ...  64. 113.  93.]]


In [57]:
np.random.seed(0)
requests = np.random.poisson(lam=200, size=1440).reshape(24, 60)
requests

array([[202, 204, 197, ..., 182, 203, 203],
       [206, 221, 197, ..., 229, 205, 191],
       [205, 194, 200, ..., 173, 188, 182],
       ...,
       [199, 198, 202, ..., 196, 187, 208],
       [203, 243, 190, ..., 184, 210, 188],
       [157, 202, 163, ..., 214, 202, 177]])

In [59]:
#Identify peak traffic hours
hourly_total = requests.sum(axis=1)
peak_hour = np.argmax(hourly_total)
print("Peak traffic hour:", peak_hour)

Peak traffic hour: 14


In [60]:
#Detect sudden traffic spikes
mean_req = requests.mean()
std_req = requests.std()
spike_threshold = mean_req + 3 * std_req
spikes = np.where(requests > spike_threshold)[0]
print("Spike indices (minutes):")
print(spikes[:10])

Spike indices (minutes):
[14]
