In [1]:
import numpy as np

In [2]:
#convert the given list into Numpy Array
original_list = [12.23, 13.32, 100, 36.32]
result = np.array(original_list)
print(result)

[ 12.23  13.32 100.    36.32]


In [3]:
#create a 3*3 matrix ranging from 2 to 10
matrix = np.arange(2, 11).reshape(3,3)
print(matrix)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [8]:
#create a null vector and update 6th value to 11
arr = np.zeros(10)
print(arr)
arr[5] = 11
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 0.  0.  0.  0.  0. 11.  0.  0.  0.  0.]


In [11]:
#wite a program to reverse an array
original_array = np.array([12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37])
reverse_array = np.flip(original_array)
print(reverse_array)

[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


In [16]:
#create an array with one on the border and 0 inside 
matrix = np.zeros((5, 5))
matrix[0, :] = 1
matrix[-1, :] = 1
matrix[:, 0] = 1
matrix[:, -1] = 1
print(matrix)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [20]:
#to add a border of zeroes around an existing array
matrix = np.ones(9).reshape(3,3)
bordered_matrix = np.pad(matrix, pad_width = 1, mode = 'constant', constant_values = 0)
print(bordered_matrix)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [22]:
#To create a 8*8 matrix and fill it with checker board pattern
checker_board = np.zeros((8,8), dtype = 'int')
checker_board[1::2, ::2] = 1
checker_board[::2, 1::2] = 1
print(checker_board)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [23]:
#List to array 
lst = [1,2,3,4,5,6,7,8]
arr1 =np.array(lst)
print(arr1)

[1 2 3 4 5 6 7 8]


In [24]:
#Tuple to array
Tuple = (8,4,6,1,2,3)
arr = np.array(Tuple).reshape(2,3)
print(arr)

[[8 4 6]
 [1 2 3]]


In [50]:
#To append values at the end of array
arr1 = np.array([10,20,30])
arr2 = np.array([40,50,60,70,80,90])
result = np.concatenate((arr1, arr2))
print(result)

[10 20 30 40 50 60 70 80 90]


In [36]:
#To find the size of array
#To find the length of one array element in bytes
#To find total bytes consumed by elements
arr = np.array([1,2,3], dtype = 'int64')
print(f"Size of the array : {arr.size}")
print(f"Length of one array element in bytes : {arr.itemsize}")
print(f"Total bytes consumed by elements of an array : {arr.size * arr.itemsize}")

Size of the array : 3
Length of one array element in bytes : 8
Total bytes consumed by elements of an array : 24


In [37]:
#To find the common values between two arrays
arr1 = np.array([0,10,20,40,60])
arr2 = np.array([10,30,40])
result = np.intersect1d(arr1, arr2)
print(result)

[10 40]


In [44]:
#Program to create a contigous faltten array
arr = np.array([[10,20,30],[20,30,40]])
result = arr.flatten()
print(result)

[10 20 30 20 30 40]


In [49]:
#Program to change the data type of an array
arr = np.array([[2,4,6],[6,8,10]])
print(f"Data Type of arr : {arr.dtype}")
new_arr = arr.astype(dtype = 'float64')
print(new_arr)
print(f"New data type : {new_arr.dtype}")

Data Type of arr : int32
[[ 2.  4.  6.]
 [ 6.  8. 10.]]
New data type : float64


In [56]:
#Program to concatenate two dimensional array
arr1 = np.array([[0,1,3],[5,7,9]])
arr2 = np.array([[0,2,4],[6,8,10]])
concat = np.concatenate((arr1, arr2),axis = 1).reshape(2,6)
print(concat)

[[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]


In [57]:
#create an array of size 3*4 and multiply every element with 3
matrix = np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11]])
print("Original matrix :")
print(matrix)
result = matrix * 3
print("New Matrix : ")
print(result)

Original matrix :
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
New Matrix : 
[[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]


In [60]:
#To convert numpy array into list data structure
matrix = np.array([[0,1],[2,3],[4,5]])
print("Original matrix")
print(matrix)
lst = matrix.tolist()
print("New Array")
print(lst)

Original matrix
[[0 1]
 [2 3]
 [4 5]]
New Array
[[0, 1], [2, 3], [4, 5]]


In [2]:
import numpy as np

In [4]:
#program to find the real and imaginary parts of an array of complex numbers.
arr = np.array([1.00000000+0.j, 0.70710678+0.70710678j])
print("Real part of the array:")
print(arr.real)
print("Imaginary part of the array:")
print(arr.imag)

Real part of the array:
[1.         0.70710678]
Imaginary part of the array:
[0.         0.70710678]


In [6]:
#program to find the set difference of two arrays
arr1 = np.array([0, 10, 20, 40, 60, 80])
arr2 = np.array([10, 30, 40, 50, 70, 90])
set_diff = np.setdiff1d(arr1, arr2)
print(set_diff)


[ 0 20 60 80]


In [10]:
#program to find the set exclusive-or of two arrays
arr1 = np.array([0, 10, 20, 40, 60, 80])
arr2 = np.array([10, 30, 40, 50, 70])
union = np.setxor1d(arr1, arr2)
print(union)

[ 0 20 30 50 60 70 80]


In [11]:
a = np.array([1,2])
b = np.array([4,5])


In [12]:
print(a>b)

[False False]


In [13]:
print(a>=b)

[False False]


In [14]:
print(a<b)

[ True  True]


In [15]:
print(a<=b)

[ True  True]


In [16]:
#Write a Python program to save a NumPy array to a text file.
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.savetxt("array_data.txt", arr, fmt = "%d")

In [17]:
#Python program to create a 3-D array with ones on a diagonal and zeros elsewhere.
diagnoal_matrix = np.eye(3, dtype = 'int32')
diagnoal_matrix

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [18]:
matrix = np.eye(5, dtype = 'int32')
matrix

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [1]:
import numpy as np

In [8]:
#Progarm to create lower-triangular matrices
matrix = np.zeros((4,3))
for i in range(1,4):
    matrix[i , :i] = 1
matrix

array([[0., 0., 0.],
       [1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

In [13]:
#program to make an array immutable (read-only)
arr = np.array([10,20,30,40,50])
arr.flags.writeable = False
print("Test the array is read-only or not:")

print("Try to change the value of the first element:")
arr[0] = 1

Test the array is read-only or not:
Try to change the value of the first element:


ValueError: assignment destination is read-only

In [14]:
#program to convert a NumPy array into Python list structure.
arr = np.array([ 0.26153123, 0.52760141, 0.5718299, 0.5927067, 0.7831874, 0.69746349, 0.35399976, 0.99469633, 0.0694458, 0.54711478])
print("Original Array: ")
print(arr)
print("Array values with precision 3:")
print(np.round(arr,3))

Original Array: 
[0.26153123 0.52760141 0.5718299  0.5927067  0.7831874  0.69746349
 0.35399976 0.99469633 0.0694458  0.54711478]
Array values with precision 3:
[0.262 0.528 0.572 0.593 0.783 0.697 0.354 0.995 0.069 0.547]


In [23]:
#program to suppresses the use of scientific notation for small numbers in numpy array.
import numpy as np

arr = np.array([1.6e-10, 1.6e+00, 1.2e+03, 2.35e-01])

print("Original array elements:")
print(arr)

print("Print array values with precision 3:")
with np.printoptions(precision=3, suppress=True):
    print(arr)


Original array elements:
[   0.       1.6   1200.       0.235]
Print array values with precision 3:
[   0.       1.6   1200.       0.235]


In [25]:
#program to how to add an extra column to an numpy array.
arr = np.array([[10,20,30],[40,50,60]])
extra_column = np.array([100,200])
result = np.column_stack((arr, extra_column))
print(result)

[[ 10  20  30 100]
 [ 40  50  60 200]]


In [30]:
#program to remove specific elements in a numpy array
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
print("Original array:")
print(arr)
result = np.delete(arr, [0,3,4])
print(result)

Original array:
[ 10  20  30  40  50  60  70  80  90 100]
[ 20  30  60  70  80  90 100]
